services:
  - type: web
    name: chainintel
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 1 -t 120 --graceful-timeout 30 -b 0.0.0.0:$PORT app.app:app
    healthCheckPath: /health
    autoDeploy: true
  