services:
  - type: web
    name: chainintel
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app/app.py
    envVars:
      - key: PORT
        value: 7860
